lrf_to_grid_node:
  ros__parameters:
    lrf_to_grid:
      topic_name:
        map: "/lrf/map"
        storage_map: "/lrf/storage_map"
        laser: "/scan"
        cloud: "/glim_ros/points"
        # cloud: "/demo_cam/mycamera/points_demo"
        # cloud: "/livox/lidar"
      tf_frame:
        map_frame: "map"
        robot_frame: "base_link"
      add_cell: false
      storage_map:
        publish_rate: 1.0 #[s]
        que_size: 5
      filter:
        voxelgrid_size: 0.2
        z_max: 1.5
        z_min: 0.1
      grid_map_info:
        resolution: 0.03 #[m] def 0.05
        # origin: [-5.0,-5.0,0.0]
        width: 25.0 #[m]
        height: 25.0 #[m]
