lrf_to_grid_node:
  ros__parameters:
    lrf_to_grid:
      topic_name:
        map: "/lrf/map"
        laser: "/scan"
        cloud: "/glim_ros/points"
        # cloud: "/demo_cam/mycamera/points_demo"
        # cloud: "/livox/lidar"
      tf_frame:
        map_frame: "map"
        robot_frame: "base_link"
      add_cell: false
      filter:
        voxelgrid_size: 0.01
        z_max: 1.5
        z_min: 0.1
      grid_map_info:
        resolution: 0.2 #[m] def 0.05
        # origin: [-5.0,-5.0,0.0]
        width: 15.0 #[m]
        height: 15.0 #[m]
