mpc_path_planning_node:
  ros__parameters:
    mpc_path_planning:
      topic_name:
        map: "/map"
        target: "/goal_pose"
        grid_path: "mpc_path_planning/grid_path"
        opti_path: "mpc_path_planning/opti_path"
        cmd_vel: "/cmd_vel"
      tf_frame:
        map_frame: "map"
        odom_frame: "odom"
        robot_frame: "base_link"
      planning_period: 0.001 #[s]
      control_period: 0.005 #[s]
      goal:
        pos_range: 0.05
        angle_range: 1.0
        min_vel_range: 0.005
        min_angular_range: 0.01
      mpc:
        dt: 0.1 # 0.135
        horizon_time: 5.0
        max_vel: 1.2
        max_angular: 2.0
        max_acc: 3.924 # 0.98
        max_angular_acc: 4.9 #1.0
        weight:
          state: [1.0, 0.0, 1.0, 200.0, 200.0, 50.0]
          final_state: [1.0, 0.0, 1.0, 200.0, 200.0, 100.0]
          control: [2.0, 0.0, 2.0]
        ipopt:
          sb: "yes" # コンソールにヘッダを出力しない
          # linear_solver: "numps" # numpsは遅い ma27はHSLライブラリ必要 (numps:40msくらい,ma27:10msくらい)
          linear_solver: "ma27" # numpsは遅い ma27はHSLライブラリ必要 (numps:40msくらい,ma27:10msくらい)
          max_iter: 500
          acceptable_tol: 0.000001
          compl_inf_tol: 0.0001
        grid_path_planner: "a_star"
