mpc_path_planning_node:
  ros__parameters:
    mpc_path_planning:
      topic_name:
        map: "/map"
        target: "/goal_pose"
        grid_path: "mpc_path_planning/grid_path"
        opti_path: "mpc_path_planning/opti_path"
      tf_frame:
        map_frame: "map"
        odom_frame: "odom"
        robot_frame: "base_link"
      control_period: 0.001
