pointcloud_to_grid_node:
  ros__parameters:
    pointcloud_to_grid:
      topic_name:
        map: "/map"
        storage_map: "/storage_map"
        cloud: "/glim_ros/points"
        # cloud: "/demo_cam/mycamera/points_demo"
        # cloud: "/livox/lidar"
      tf_frame:
        map_frame: "map"
      period: 0.1 #[s]
      add_cell: true
      que:
        size: 10
      filter:
        voxelgrid_size: 0.1
        z_max: 1.0
        z_min: 0.3
      grid_map_info:
        resolution: 0.1 #[m] def 0.05
        # origin: [-5.0,-5.0,0.0]
        width: 25.0 #[m]
        height: 25.0 #[m]
