pointcloud_to_grid_node:
  ros__parameters:
    pointcloud_to_grid:
      topic_name:
        map: "/map"
        cloud: "/livox/lidar"
      tf_frame:
        map_frame: "map"
      control_period: 0.001
      filter:
        voxelgrid_size: 0.04
        z_max: 2.0
        z_min: 0.5
